---
- name: Show version
  hosts: all
  gather_facts: False
  
  tasks:

   - name: run show version and check to see if output contains Dell
    dellos6_command:
      commands: show version
      wait_for: result[0] contains Dell
